package engineering.model;
// Generated Jul 28, 2023, 9:23:27 AM by Hibernate Tools 6.0.2.Final

/**
 * Author generated by hbm2java
 */
public class Author implements java.io.Serializable {

	private int authorId;
	private String authorName;

	public Author() {
	}

	public Author(int authorId) {
		this.authorId = authorId;
	}

	public Author(int authorId, String authorName) {
		this.authorId = authorId;
		this.authorName = authorName;
	}

	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public String getAuthorName() {
		return this.authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
}

}

